// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 29/10/2025, 22:01:45
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Stefano/Programmi/t1diario/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stefano/Programmi/t1diario/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stefano/Programmi/t1diario/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stefano/Programmi/t1diario/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stefano/Programmi/t1diario/plugins/**/*.{js,ts,mjs}","C:/Users/Stefano/Programmi/t1diario/composables/**/*.{js,ts,mjs}","C:/Users/Stefano/Programmi/t1diario/utils/**/*.{js,ts,mjs}","C:/Users/Stefano/Programmi/t1diario/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stefano/Programmi/t1diario/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stefano/Programmi/t1diario/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Stefano/Programmi/t1diario/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;