// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/30/2025, 11:23:19 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/stefano/Progetti/t1diario/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/stefano/Progetti/t1diario/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/stefano/Progetti/t1diario/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/stefano/Progetti/t1diario/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/stefano/Progetti/t1diario/plugins/**/*.{js,ts,mjs}","/Users/stefano/Progetti/t1diario/composables/**/*.{js,ts,mjs}","/Users/stefano/Progetti/t1diario/utils/**/*.{js,ts,mjs}","/Users/stefano/Progetti/t1diario/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/stefano/Progetti/t1diario/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/stefano/Progetti/t1diario/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/stefano/Progetti/t1diario/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;