name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'
      - 'pages/**'
      - 'components/**'
      - 'app.vue'
      - 'nuxt.config.ts'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate static site
        env:
          # For project pages (https://USERNAME.github.io/REPO/). Change to '/' for user/org pages.
          NUXT_APP_BASE_URL: ${{ format('/{0}/', github.event.repository.name) }}
          NUXT_PUBLIC_GISCUS_REPO: ${{ secrets.NUXT_PUBLIC_GISCUS_REPO }}
          NUXT_PUBLIC_GISCUS_REPO_ID: ${{ secrets.NUXT_PUBLIC_GISCUS_REPO_ID }}
          NUXT_PUBLIC_GISCUS_CATEGORY: ${{ secrets.NUXT_PUBLIC_GISCUS_CATEGORY }}
          NUXT_PUBLIC_GISCUS_CATEGORY_ID: ${{ secrets.NUXT_PUBLIC_GISCUS_CATEGORY_ID }}
          NUXT_PUBLIC_GISCUS_MAPPING: ${{ secrets.NUXT_PUBLIC_GISCUS_MAPPING }}
          NUXT_PUBLIC_GISCUS_STRICT: ${{ secrets.NUXT_PUBLIC_GISCUS_STRICT }}
          NUXT_PUBLIC_GISCUS_REACTIONS: ${{ secrets.NUXT_PUBLIC_GISCUS_REACTIONS }}
          NUXT_PUBLIC_GISCUS_EMIT_METADATA: ${{ secrets.NUXT_PUBLIC_GISCUS_EMIT_METADATA }}
          NUXT_PUBLIC_GISCUS_INPUT_POSITION: ${{ secrets.NUXT_PUBLIC_GISCUS_INPUT_POSITION }}
          NUXT_PUBLIC_GISCUS_THEME: ${{ secrets.NUXT_PUBLIC_GISCUS_THEME }}
          NUXT_PUBLIC_GISCUS_LANG: ${{ secrets.NUXT_PUBLIC_GISCUS_LANG }}
          NUXT_PUBLIC_GISCUS_LOADING: ${{ secrets.NUXT_PUBLIC_GISCUS_LOADING }}
        run: npm run generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
